# Generated by Django 2.0.1 on 2018-01-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='logo',
            field=models.FileField(default='bank_logos/default.png', upload_to='bank_logos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='logo',
            field=models.FileField(default='category_icons/default.png', upload_to='category_icons/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.FileField(default='avatars/default.png', upload_to='avatars/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
