# Generated by Django 2.0.1 on 2018-01-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_auto_20180124_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='logo',
            field=models.FileField(default='bank_logos/default.png', upload_to='bank_logos/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='logo',
            field=models.FileField(default='category_icons/default.png', upload_to='category_icons/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(default='avatars/default.png', upload_to='avatars/'),
        ),
    ]
