# Generated by Django 2.0.1 on 2018-02-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0006_auto_20180201_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='repeat_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
