# Generated by Django 2.0.1 on 2018-02-22 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0008_transaction_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_spending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='default_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='savings.Account'),
        ),
    ]
