# Generated by Django 2.0.1 on 2018-03-02 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0010_auto_20180302_0704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='display_name',
        ),
    ]
