# Generated by Django 2.0.1 on 2018-03-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0011_remove_profile_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='logo',
            field=models.ImageField(default='bank_logos/default.png', upload_to='bank_logos/'),
        ),
    ]
