# Generated by Django 2.0.1 on 2018-03-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0012_auto_20180307_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='logo',
            field=models.ImageField(default='static/images/bank_logos/default.png', upload_to='static/images/bank_logos/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='logo',
            field=models.FileField(default='static/images/category_icons/default.png', upload_to='static/images/category_icons/'),
        ),
    ]
