# Generated by Django 2.0.1 on 2018-03-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0015_auto_20180315_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='setting_max_transactions_days',
            field=models.IntegerField(default=10),
        ),
    ]
