# Generated by Django 2.0.1 on 2019-09-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0016_profile_setting_max_transactions_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='logo',
            field=models.ImageField(default='static/images/bank_logos/default.png', upload_to='bank_logos/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(default='static/images/avatars/default.png', upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='repeat_time',
            field=models.DecimalField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28')], decimal_places=0, max_digits=2, null=True),
        ),
    ]
